version: 0.2
env:
  shell: bash
  git-credential-helper: yes
  variables:
    REGION: "ap-northeast-2"
    ENVIRONMENT: test
#    // Not needed any more because this script will modified the deploy manifest directly.
#    IMAGE_TAG_KEY: "/application/flightspecial/container/image/main/tag"
phases:
  install:
    # runtime-versions:
    #   java: corretto11
    commands:
      - apt-get update
      - apt-get install -y jq
  pre_build:
    commands:
      - echo "Print awscli version"
      - aws --version
      - export AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output=text) && echo $AWS_ACCOUNT_ID
      - echo "### SRC_VERISON-> ${CODEBUILD_RESOLVED_SOURCE_VERSION} | Logging-in to ECR"
      - docker login --username AWS -p $(aws ecr get-login-password --region ${REGION}) ${ECR_REPO_URI}
      #     Mix with one alphabet "t" to avoid floating type conversion in helm operation.
      - export TAG="t${CODEBUILD_RESOLVED_SOURCE_VERSION}"
      - export TAG=$(echo $TAG | sed -e "s/\.//g"| tr '[:upper:]' '[:lower:]')
      - export TAG=$(echo "${TAG:0:8}")
      - export IMAGE_TAG="${TAG}"
      - echo "## TAG-> ${TAG}"
      - echo "### Retrieving database information..."
      - export DATABASE_ENDPOINT=$(aws rds describe-db-instances --query "DBInstances[?DBInstanceIdentifier=='flightspecials-test-postgres-db'].Endpoint.Address" --output text) && echo $DATABASE_ENDPOINT
      - export DATABASE_PORT=$(aws rds describe-db-instances --query "DBInstances[?DBInstanceIdentifier=='flightspecials-test-postgres-db'].Endpoint.Port" --output text) && echo $DATABASE_PORT
      #      - [TODO] DATABASE_USERNAME: Currently fixed from secrets manager.
      # - export DATABASE_USERNAME=flightspecial_db_credentials_test
      - export DATABASE_USERNAME=$(aws secretsmanager list-secrets --filters Key=tag-value,Values="arn:aws:rds:ap-northeast-2:${AWS_ACCOUNT_ID}:db:flightspecials-test-postgres-db" --query "SecretList[0].Name" --output text) && echo $DATABASE_USERNAME
      - env
  build:
    commands:
      - |
        echo "### Building FlightSpecials application ###"
        chmod +x ./gradlew
        ./gradlew clean build --no-daemon -x test
      - |
        echo "### Building Container Image ###"
        echo $CODEBUILD_SRC_DIR
        echo Build started on `date`
        echo Building the Docker image...
        docker build -t $ECR_REPO_URI:latest ./
        docker images
        docker tag $ECR_REPO_URI:latest $ECR_REPO_URI:$IMAGE_TAG
      - |
        echo "### Pushing Container Image ###"
        docker push $ECR_REPO_URI:latest
        docker push $ECR_REPO_URI:$IMAGE_TAG
  post_build:
    commands:
      #      - |
      #        echo "### Pushing container image tag to SSM for reuse ###"
      #        aws ssm put-parameter --name $IMAGE_TAG_KEY --value $IMAGE_TAG --type String --region $REGION --overwrite
      - echo "${IMAGE_TAG}" >> build_output.txt
      - git config --global --replace-all credential.helper '!aws codecommit credential-helper $@'
      #        [TODO] 아래 클론 시의 Repository URL 값도 CodeBuild의 환경변수 혹은 CloudFormation Output으로부터 주입되면 좋습니다.
      - |
        echo "### Update value to manifest repository ###"
        git clone https://git-codecommit.ap-northeast-2.amazonaws.com/v1/repos/flightspecials-configuration
        cd flightspecials-configuration
        ls
        cat values-template.yaml | envsubst > ./values.yaml
        cat ./values.yaml
        git status
        git config user.email "anyone@example.com"
        git config user.name "FlightSpecial Developer"
        git add .
        git commit -m "Updated image tag to $IMAGE_TAG"
        git log --oneline
        git remote -v
        git push -u origin main
artifacts:
  files:
    - build_output.txt
    - interface/build/libs/flightspecials.jar
cache:
  paths:
    - '/root/.gradle/caches/**/*'
